### ISSUE TITLE
https://os.mbed.com/docs/latest/tutorials/quick-start-offline.html has a broken link for the download

### ISSUE THREAD

**Issue by UDXS** [ARMmbed/Handbook#461]

**Comment by AnotherButler** [comment]
@UDXS Could you please clarify which link is broken? I can open the Windows installer link, the Python link, the CoolTerm link and the PuTTy link. Is one of those giving you trouble, or is it another?

**Comment by UDXS** [comment]
It was the Windows Installer one. It gives a 404 error.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by AnotherButler** [comment]
@UDXS Could you please try that link again here: https://os.mbed.com/docs/latest/tutorials/quick-start-offline.html

I'd like to be sure that's fixed. Thanks so much.

**Comment by UDXS** [comment]
@AnotherButler Sorry, but it doesn't appear to work.

[Here is a video of it not working](https://youtu.be/J4dqwj2JMPU)

Thanks!

**Comment by maclobdell** [comment]
I can confirm the issue.   

A link at the following page is bad: 
https://os.mbed.com/docs/latest/tutorials/quick-start-offline.html

The section is: 

Windows
1. Install Mbed CLI
Download and run the Mbed CLI Windows .exe installer.

The bad link is this going to:
https://github.com/ARMmbed/mbed-cli-windows-installer/releases

The reason it is bad is because it is a private repo.  not sure why it is private, but it looks like there is an alternative section in the docs that had a link to a windows installer that is good.  

See location: 
https://os.mbed.com/docs/v5.7/tools/installing-with-the-windows-installer.html

Section: 

Running the installer
Download the latest executable from mbed-windows-installer v0.4.3.
Run mbed_installer_v042.exe.

Please fix asap!  This is a critical one.

Thanks!

**Comment by AnotherButler** [comment]
Does this PR adequately fix the issue? https://github.com/ARMmbed/Handbook/pull/469

**Comment by UDXS** [comment]
Yes, I believe it does.
I will close this as long as that PR is accepted.
Thank you, @AnotherButler and @maclobdell
